### ISSUE TITLE
Please continue development.

### ISSUE THREAD

**Issue by ManuelSchneid3r** [jamesmorgan/github-explorer#40]
See topic :wink:

**Comment by jamesmorgan** [comment]
Hi @ManuelSchneid3r thanks for the prod 😃 . I will endeavour to find some time to carry on with this project. Its difficult as I primarily use a OSX for most of dev nowadays and find it hard to dev Mint on my Mac. Also I found last time I did some work I found it very frustrating as good documentation is hard to find/impossible on cinnamon/soup/LM. I am more than welcome to accept PR's and help on this. 

I have created a new project to try and manage this process - https://github.com/jamesmorgan/github-explorer/projects/1 - please feel free to pick up or add any issues and we can move this project forward.

**Comment by ManuelSchneid3r** [comment]
Why dont you develop a platformindependent tray solution? Just a hint:D

**Comment by jamesmorgan** [comment]
Interestingly enough I started looking into electron at the weekend and will give it ago. I'm still unsure of LM cinnamon support but hope to create a working prototype in the next few weeks and I'll be sure to update you. :)

**Comment by jamesmorgan** [comment]
FYI - I started to play about with electron over the weekend and made a start on a basic menubar app - currently only tested on OSX but in theory should work on linux - https://github.com/jamesmorgan/github-explorer-electron - once I have more features in play I will investigate how to plublish it properly
